title: Sulochana Moola # your name (or website title) here
logo: "/images/1616444724977.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist
  <br><br>
  Machine Learning Engineer 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: 287272802 # your Google Analytics tracking ID here
